#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/lexus

PRODUCT_COPY_FILES += \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/FTM/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/acdb_cal.acdb \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/FTM/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/workspaceFileXml.qwsp \
    vendor/oneplus/lexus/proprietary/odm/etc/acdbdata/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/acdb_cal.acdb \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/HP_COMMON.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_COMMON.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/HP_GAME1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_GAME1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/HP_GAME2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_GAME2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/HP_MOVIE.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_MOVIE.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/HP_MOVIE2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_MOVIE2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/HP_MUSIC.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_MUSIC.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/HP_VOICE.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_VOICE.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPAT_AUDIOX_ROOMMODEL_MOVIE_SPK.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPAT_AUDIOX_ROOMMODEL_MOVIE_SPK.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPAT_AUDIOX_ROOMMODEL_MUSIC_SPK.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPAT_AUDIOX_ROOMMODEL_MUSIC_SPK.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl3.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl4.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl5.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl3.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl4.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl5.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl3.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl4.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl5.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl3.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl4.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl5.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl3.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl4.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl5.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl3.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl4.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl5.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl1.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl2.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl3.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl4.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl5.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/camera_engmode.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/camera_engmode.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/cfr_bin/CFR_OPlus_EF017_UW_snapshot.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_OPlus_EF017_UW_snapshot.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/cfr_bin/CFR_lexusfront.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_lexusfront.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/cfr_bin/CFR_lexusmain.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_lexusmain.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/cfr_bin/CFR_lexuswide.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_lexuswide.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/camera_third_party_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_third_party_feature_config.protobuf \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/camera_unit_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/camera_unit_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_feature_config.protobuf \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/oplus_camera_algo_switch_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_switch_config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/oplus_camera_algo_traversal_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_traversal_config.json \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/oplus_camera_aps_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_aps_config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/oplus_camera_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/oplus_camera_preview_decision_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_preview_decision_config.json \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/oplus_preview_decision_params.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_preview_decision_params.json \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/pickref_params.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/config/pickref_params.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/quick_visibility_white_list:$(TARGET_COPY_OUT_ODM)/etc/camera/config/quick_visibility_white_list \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/sr_params.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/config/sr_params.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/config/video_beauty_default_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/video_beauty_default_config \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/settings_fdc.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/camera/settings_fdc_lite.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc_lite.txt \
    vendor/oneplus/lexus/proprietary/odm/etc/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/mixer_paths.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/resourcemanager.xml:$(TARGET_COPY_OUT_ODM)/etc/resourcemanager.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/json_list:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/json_list \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/lexus_qrd_ois_system.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lexus_qrd_ois_system.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/lux_aod.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lux_aod.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_alsps.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_alsps_hw_tcs3720.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_alsps_hw_tcs3720.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_bmi26x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_bmi26x.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_freefall.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_freefall.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_mmc56x3x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_mmc56x3x.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_oplus_measurement.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_oplus_measurement.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_oplus_smart_prox.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_oplus_smart_prox.json \
    vendor/oneplus/lexus/proprietary/odm/etc/sensor/config/palawan_mtp_pocket.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_pocket.json \
    vendor/oneplus/lexus/proprietary/odm/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_ODM)/etc/usecaseKvManager.xml \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/kiwi/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/regdb.bin \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/kiwi/regdb_version:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/regdb_version \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/qca6750/bdwlan.b0e:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.b0e \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/qca6750/bdwlan.b0i:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.b0i \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/qca6750/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.elf \
    vendor/oneplus/lexus/proprietary/odm/etc/wifi/qca6750/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/regdb.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/fastchg/24881/charging_hyper_mode_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/24881/charging_hyper_mode_config.txt \
    vendor/oneplus/lexus/proprietary/odm/firmware/fastchg/bms_heating_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/bms_heating_config.txt \
    vendor/oneplus/lexus/proprietary/odm/firmware/fastchg/charging_thermal_config_default.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charging_thermal_config_default.txt \
    vendor/oneplus/lexus/proprietary/odm/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_ODM)/firmware/tfa98xx.cnt \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/FW_S3910_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/FW_S3910_TIANMA.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/FW_S3910_TIANMA_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/FW_S3910_TIANMA_FAE.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/FW_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/FW_S3910_TIANMA_HBP.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/FW_S3910_TIANMA_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/FW_S3910_TIANMA_HBP_FAE.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/GloveDetect.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/GloveDetect.tflite \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_ALGO.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_ALGO.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_ALGO_HWASAN.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_ALGO_HWASAN.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_HAL.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIB_S3910_TIANMA_HBP_TS_HAL.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIMIT_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIMIT_S3910_TIANMA_HBP.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/LIMIT_S3910_TIANMA_HBP_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/LIMIT_S3910_TIANMA_HBP_AGING.img \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/libIfp.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/libIfp.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/libaifilm.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/libaifilm.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/model.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/model.so \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/model.tflite \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/sys_edge_touch_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/sys_edge_touch_config.xml \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/sys_touch_algo_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/sys_touch_algo_feature_config.xml \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/sys_touch_function_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/sys_touch_function_feature_config.xml \
    vendor/oneplus/lexus/proprietary/odm/firmware/tp/24881/sys_touch_scene_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24881/sys_touch_scene_config.xml \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/MICRON-MT256GBEAZ4U31.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/MICRON-MT256GBEAZ4U31.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/MICRON-MT512GAYAZ4U31.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/MICRON-MT512GAYAZ4U31.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/SKhynix-HN8T15DEHKX075.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T15DEHKX075.bin \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh:$(TARGET_COPY_OUT_ODM)/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh \
    vendor/oneplus/lexus/proprietary/odm/firmware/ufs/ufs_version_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/ufs/ufs_version_config.xml \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.sensormodule.lexusfront.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lexusfront.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.sensormodule.lexusfront_DVT.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lexusfront_DVT.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.sensormodule.lexusmain.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lexusmain.bin \
    vendor/oneplus/lexus/proprietary/odm/lib64/camera/com.qti.sensormodule.lexuswide.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lexuswide.bin \
    vendor/oneplus/lexus/proprietary/vendor/etc/card-defs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/card-defs.xml \
    vendor/oneplus/lexus/proprietary/vendor/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usecaseKvManager.xml

PRODUCT_PACKAGES += \
    com.qti.sensor.lexusfront \
    com.qti.sensor.lexusmain \
    com.qti.sensor.lexuswide \
    libtfa98xx
